### ISSUE TITLE
Branding For Piston CLI

### ISSUE THREAD

**Issue by Shivansh-007** [Piston-CLI/piston-cli#18]
## Description
At present, this project does not have a logo or a banner. A that logo will be used in our `README.md`, on our [discord server](https://discord.gg/c7dZ4zdGQT) for now. Banner would also server the same purpose.

- **What is piston-cli?**
A universal shell supporting 36+ languages, in terminal code editor with syntax highlight, code compiler (36+ languages). It can run code from pastebin links and files too. 

- **Abstract based/ Letter based**
Hmm, try both of them, we can choose anyone from them :D .

- **Any accent colour.**
Green, terminal look.

- **Any particular shape**
Logo should be circular in shape.
Banner should be rectangle _ish_ with a size of 640×320px (1280×640px for best display).

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by KaranSinghBisht** [comment]
Hello Shivansh 👋, I would like to work on this.

**Comment by Shivansh-007** [comment]
Sure! Assigned it to you :D

**Comment by Shivansh-007** [comment]
This user has left from our community.   

Another person will be assigned to take over this issue. Comment below if you want to help us out :D.

**Comment by melaniietong** [comment]
Hello! I would like to give this a shot. Could you give more insight into what you want the logo to look like? Any mood/feeling? Any reference images?

**Comment by Shivansh-007** [comment]
> Hello! I would like to give this a shot. Could you give more insight into what you want the logo to look like? Any mood/feeling? Any reference images?

Hello there! Thanks for showing interest in Piston-CLI. Maybe you could join our [discord](https://discord.gg/c7dZ4zdGQT) server where we could do rest of the discussions to keep this clean :) .
