### ISSUE TITLE
Better CLI Error Handling

### ISSUE THREAD

**Issue by Shivansh-007** [Piston-CLI/piston-cli#36]
## Description
Currently, innocent Piston CLI errors such as "No closing quotation" or "missing required argument" are not being handled by the command error handler as we have no error handler as of now. As a result, the the CLI displays lots of Errors which aren't understandable. 

In short we have no custom error error handler, and the default one doesn't emit much useful information. We may do better than this.

## Proposed Implementation
Investigate the problem, create logic to handle these types of errors, and open a PR to [Piston CLI](https://github.com/Shivansh-007/piston-cli).

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Shivansh-007** [comment]
Errors to be include in the handled include:

- `NewConnectionError` - caused when you are disconnected from the internet.

![Screenshot from 2021-04-12 07-49-25](https://user-images.githubusercontent.com/69356296/114332325-a3f8ef00-9b63-11eb-9c55-5a397f390838.png)

- `AttributeError` - When `piston-cli/config.yml` is present but empty

![Screenshot from 2021-04-12 07-49-07](https://user-images.githubusercontent.com/69356296/114332335-a8250c80-9b63-11eb-92f1-de1fa477f53b.png)

**Comment by H4CKY54CK** [comment]
I can look into this.

**Comment by WANTED10** [comment]
### 

> `_**Same!**_`

**Comment by WANTED10** [comment]
I can look into this aswell 👍.

**Comment by Shivansh-007** [comment]
> I can look into this aswell .

Hey @WANTED10 thanks for showing interest in this issue but it looks like @H4CKY54CK has already being assigned, and this is a rather small issue. You can look into the [other issues](https://github.com/Shivansh-007/piston-cli/issues) opened on this repository and get assigned to the one you are interested in.

**Comment by Shivansh-007** [comment]
#50 Closes this.
