### ISSUE TITLE
Make prompt continuation and start configurable

### ISSUE THREAD

**Issue by Shivansh-007** [Piston-CLI/piston-cli#54]
Currently the prompt continuation is default to `...` and prompt continuation to `>>>` this should be configurable.

**Comment by SatvikR** [comment]
I am willing to pr for this. How do you want the user to be able to configure this? (config file, ask on startup, etc.)

**Comment by Shivansh-007** [comment]
Hey @SatvikR, thankyou for showing interest in this.

Users should be able to configure this in their `~/.config/piston/config.yml`(and accordingly for other OS). We already have built a nice configuration setup. You need to make another python file in the [`configuration folder`](https://github.com/Piston-CLI/piston-cli/tree/verson-1.4.0/piston/configuration). You can see examples in the other files on how to do it.

If you come across any difficulty you can either ask on the [discord server](https://discord.gg/5bJD3AxR) or here in this issue.

Good luck!
