### ISSUE TITLE
Keyboard Interrupt

### ISSUE THREAD

**Issue by pranavbaburaj** [Piston-CLI/piston-cli#62]
Keyboard interrupt with prompts

**Comment by Shivansh-007** [comment]
This has still not being fixed

![Screenshot from 2021-05-27 19-32-12](https://user-images.githubusercontent.com/69356296/119841200-3e01d480-bf23-11eb-83b4-028d2ff88046.png)

**Comment by math280h** [comment]
@Shivansh-007 I can take a look at this if needed

**Comment by Shivansh-007** [comment]
> @Shivansh-007 I can take a look at this if needed

Sure go ahead! Assigned the issue to you
